### ISSUE TITLE
Missing text styles: "undercurl" and "standout"

### ISSUE THREAD

**Issue by penicolas** [jacoborus/estilo#19]
According to the documentation `:help highlight-term`:

```
term={attr-list}	
	attr-list is a comma separated list (without spaces) of the
	following items (in any order):
		bold
		underline
		undercurl	not always available
		reverse
		inverse		same as reverse
		italic
		standout
		NONE		no attributes used (used to reset it)
```

The following text styles are not defined:

 - undercurl
 - standout

**Comment by jacoborus** [comment]
I just forgot to add them. Can you tell me what `standout` style is for and how it looks please? I can't find that info

**Comment by penicolas** [comment]
It seems the same as `inverse` but `bold`. You can try it in `vim`:

```
:hi String guifg=Red guibg=Black gui=standout
:hi String
```

But I've never used before.

**Comment by jacoborus** [comment]
I can't see the difference between `standout` and `reverse` but I'm adding that style anyway. I'm curious, what vim are you working with?

**Comment by penicolas** [comment]
gVim 8.0.3:

![gvim__standout_vs_reverse](https://cloud.githubusercontent.com/assets/810787/18548244/0cb6909c-7b48-11e6-9100-f559600d2a6e.png)

**Comment by jacoborus** [comment]
@penicolas , did it work?

**Comment by penicolas** [comment]
it works really good, thanks!
