### ISSUE TITLE
Missing "guisp" option

### ISSUE THREAD

**Issue by penicolas** [jacoborus/estilo#20]
According to the documentation `:help highlight-guisp`

```
guifg={color-name}	
guibg={color-name}
guisp={color-name}
	These give the foreground (guifg), background (guibg) and special
	(guisp) color to use in the GUI.  "guisp" is used for undercurl.
```

Rel #19

But perhaps break the current format: `'fg bg style'`. Maybe not worth.

**Comment by jacoborus** [comment]
`guisp` could be the fourth value without problems. Do you need this feature?

**Comment by penicolas** [comment]
Not really.

I was migrating my [colour](https://github.com/penicolas/simplon.vim) to `estilo`  and I found this:

```
" {{{ Spelling
hi spellBad         guisp=#fcaf3e
hi spellCap         guisp=#73d216
hi spellRare        guisp=#fcaf3e
hi spellLocal       guisp=#729fcf
" }}}
```

Example of `spellCap`, `spellBad`, none:

![vim_spell](https://cloud.githubusercontent.com/assets/810787/18548811/02c6e444-7b4b-11e6-9484-7a936f308f20.png)

**Comment by jacoborus** [comment]
That's nice! I never saw that before. I'll add that feature tomorrow
