### ISSUE TITLE
What is the minimum node version for estilo to work?

### ISSUE THREAD

**Issue by Hunter-Github** [jacoborus/estilo#22]
Node 5.11.1 here:

```
$ estilo init
~/.nodebrew/node/v5.11.1/lib/node_modules/estilo/src/cli/estilo.js:5
const { resolve } = require('path')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

**Comment by jacoborus** [comment]
I'm afraid destructuring assignments are not supported in versions prior to node v6. Can you upgrade?

**Comment by Hunter-Github** [comment]
Not yet, sorry. Can `package.json` be updated to reflect the requirements?

**Comment by jacoborus** [comment]
Requirements were [already reflected in `package.json`](https://github.com/jacoborus/estilo/blob/1139628c59346bcf79530109e0fc3555a6319cc5/package.json#L38). I rather use some harmony flags on top of the bin file so uploaded a new version to npm, can you upgrade your local Estilo installation to v1.1.2 and tell me if it works please?

**Comment by Hunter-Github** [comment]
The same error so far, v.1.1.2.

**Comment by jacoborus** [comment]
What `node --v8-options | grep "in progress"` returns?

**Comment by jacoborus** [comment]
I realized that to use harmony flags to a globally installed module is not a good idea, so I made a branch without destructuring assignments. If it works for you I'll merge it with the master branch.

```sh
git clone -b no-destructuring git@github.com:jacoborus/estilo.git
cd estilo
npm install -g .
```

**Comment by Hunter-Github** [comment]
This branch works fine for me, thanks.

**Comment by jacoborus** [comment]
Great, I'll merge that branch with the main one in a couple of days

**Comment by jacoborus** [comment]
Merged
