### ISSUE TITLE
estilo add-syntax aborts while adding templates

### ISSUE THREAD

**Issue by rakr** [jacoborus/estilo#27]
hi @jacoborus 

I have tried to add a new template to a current colorscheme, but I systematically get the following error: `Aborting due an error while adding templates`.

I have tried this on an existing colorscheme as well as on a new one, and I get the same behaviour.
<img width="444" alt="___development_vim__zsh_" src="https://cloud.githubusercontent.com/assets/110558/18652371/4bde57ca-7f15-11e6-9821-a9dcfb66144d.png">

**Comment by rakr** [comment]
Using estilo v1.2.1

**Comment by jacoborus** [comment]
hi @rakr , I can't check this now, I will do it tomorrow. In the meanwhile, you can copy the blank templates you need in `estilo/syntax` folder from [here](https://github.com/jacoborus/estilo/tree/master/templates/syntax)

**Comment by rakr** [comment]
Thanks for the tip
Operating system:  Mac OS Sierra

**Comment by jacoborus** [comment]
Hi @rakr , can you upgrade estilo and try again please?

**Comment by rakr** [comment]
hi @jacoborus, upgraded, tested, it worked.
thanks mate

**Comment by jacoborus** [comment]
you're welcome!
