### ISSUE TITLE
Add support for vim-signify

### ISSUE THREAD

**Issue by jacoborus** [jacoborus/estilo#39]
Support [vim-signify](https://github.com/mhinz/vim-signify) as requested in https://github.com/jacoborus/tender.vim/pull/36

**Comment by huyvohcmc** [comment]
By support you mean we just need to create a template similar to `estilo/templates/syntax/vim-gitgutter.yml`?

**Comment by jacoborus** [comment]
done cba696c22193e3612fa34c81cebeff3084f69600
