### ISSUE TITLE
Tack on `vim-framer-syntax` to projects that use estilo?

### ISSUE THREAD

**Issue by balanceiskey** [jacoborus/estilo#49]
Hi! First of all, thanks for building such a great tool! 

I was wondering if you'd be interesting in including [vim-framer-syntax](https://github.com/balanceiskey/vim-framer-syntax) to your list of colorschemes created with estilo.

**Comment by jacoborus** [comment]
b0f734014ad50eb3094d36df357b0a70bea1cb62 

Thanks!

**Comment by jacoborus** [comment]
btw, Estilo v2 is coming ;)
