### ISSUE TITLE
Q how I can integrate estilo into my workflow

### ISSUE THREAD

**Issue by metaory** [jacoborus/estilo#50]
I currently feed my generated files from [mxcolr](https://github.com/metaory/mxcolr) to various parts, 
wondering how I can integrate `estilo` into my workflow,

I basically generate scheme files from mxc [templates](https://github.com/metaory/mxcolr/blob/master/templates) or  [plugins](https://github.com/metaory/mxcolr/blob/master/plugins)  and replace or import them later on
some sample parts of my setup;

#### Colors
- Global Colors.lua [mxc-nvim-colors.lua](https://github.com/metaory/mxcolr/blob/master/assets/samples/mxc-nvim-colors.lua)
- Base16 Colors.lua [mxc-nvim-base16.lua](https://github.com/metaory/mxcolr/blob/master/assets/samples/mxc-nvim-base16.lua)
- Global Colors.vim [root-mx.vim](https://github.com/metaory/mxcolr/blob/master/assets/samples/root-mx.vim)

#### Plugins
- Syntax _Base16_ using [nvim-base16.lua](https://github.com/siduck76/nvim-base16.lua) *Includes support for Treesitter and LSP highlight groups*
- Statusline (galaxyline), Bufferline(barbar) and the rest using global vars

**Comment by jacoborus** [comment]
First of all, you'll need a working colorscheme made with Estilo. Then you can play changing the [colors of the palettes](https://github.com/jacoborus/estilo/blob/master/docs/color-palettes.md) with the colors your tool has generated.

I've planned to add a default colorscheme to Estilo, but that could take some months. In the meantime you may try with [one the the featured ones](https://github.com/jacoborus/estilo#colorschemes-created-with-estilo) in the README file.

Have in mind that the docs are still not updated to the v2, I'll try to update them in following days
