### ISSUE TITLE
TypeError on some cmds when estilo is installed without unstable flag

### ISSUE THREAD

**Issue by prdx23** [jacoborus/estilo#53]
After installing estilo using the deno command in the readme, commands that expect input like `estilo create`, `estilo add-syntax`, `estilo add-airline` and `estilo add-lightline` give the following TypeError:

![Screenshot from 2021-10-30 22-34-47](https://user-images.githubusercontent.com/15089721/139543391-bd183eab-1b76-4c41-8700-b476996e1cca.png)

This can be fixed by adding the `--unstable` flag to the install command. I am not familiar with deno/typescript so I am not sure if this is a bug. If the unstable flag is the intended way to install then we should update the install cmd in the readme

**Comment by jacoborus** [comment]
Exactly. I just added it to the docs. Thanks!
https://github.com/jacoborus/estilo/commit/6de174e74a2f2a67aa9bdf72b0d358b7986a285d
