### ISSUE TITLE
No such file or directory (os error 2): readdir '/home/jacobo/dev/estilo/assets/syntax'

### ISSUE THREAD

**Issue by sylann** [jacoborus/estilo#61]
I have just installed deno (with the shell script, v1.37).
Immediately after that I installed estilo (copy-pasted the line from README).
I'm on MacOs Monterey.

When I try to run estilo (whatever the command, even simply estilo -h) I get the following error:

```
error: Uncaught NotFound: No such file or directory (os error 2): readdir '/home/jacobo/dev/estilo/assets/syntax'
    const fileNames = Array.from(Deno.readDirSync(folderPath)).filter(({ isFile , isSymlink  })=>isFile && !isSymlink).map(({ name  })=>name);
                                      ^
    at Object.readDirSync (ext:deno_fs/30_fs.js:151:14)
    at loadFolder (https://denopkg.com/jacoborus/estilo@master/dist/estilo.js:9034:39)
    at https://denopkg.com/jacoborus/estilo@master/dist/estilo.js:9030:16
```

I thought having a path to someone else's system on my own machine was weird.
But after checking `$DENO_INSTALL/bin/estilo`, which content is:
```
#!/bin/sh
# generated by deno install
exec deno run --allow-read --allow-write --unstable --no-config 'https://denopkg.com/jacoborus/estilo/dist/estilo.js' "$@"
```
I've seen that `/home/jacobo/dev/estilo/assets/syntax` is actually hardcoded in `dist/estilo.js`.

I have no idea what may be normal or not at this point.

Some help would be much appreciated.

**Comment by jacoborus** [comment]
It's not normal, thanks for reporting

**Comment by jacoborus** [comment]
@sylann It should be fixed now
